position_map = {
    "nhân viên": "Employee",
    "trưởng phòng": "Manager",
    "giám đốc": "Director",
    "phó giám đốc": "Deputy Director",
    "chuyên viên": "Specialist",
    "kỹ sư": "Engineer",
    "quản lý": "Supervisor",
    "thực tập sinh": "Intern",
    "trợ lý": "Assistant",
    "giảng viên": "Lecturer",
    "nghiên cứu viên": "Researcher",
    "nhân viên kinh doanh": "Salesperson",
    "chuyên gia": "Expert",
    "nhân viên chăm sóc khách hàng": "Customer Service",
    "trưởng nhóm": "Team Leader",
    "trưởng nhóm dự án": "Project Leader",
    "kế toán": "Accountant",
    "pháp lý": "Legal",
    "quản trị viên": "Administrator",
    "phân tích viên": "Analyst",
    "tư vấn viên": "Consultant",
    "giám sát": "Supervisor",
    "trưởng máy": "Machine Leader",
    "phụ vận hành": "Operation Assistant",
    "phát triển đối tác": "Partnership Developer",
    "phát triển kinh doanh": "Business Development",
    "chuyên viên nhân sự": "HR Specialist",
    "chuyên viên tuyển dụng": "Recruitment Specialist",
    "chuyên viên đào tạo": "Training Specialist",
    "chuyên viên môi giới": "Broker",
    "chuyên viên tiếp thị": "Marketing Specialist",
    "phân tích cường độ": "Strength Analyst",
    "bác sĩ": "Doctor",
    "giáo viên": "Teacher",
    "kỹ thuật viên": "Technician",
    "nhân viên vận hành": "Operations Staff",
    "chuyên viên chăm sóc khách hàng": "Customer Support Specialist",
    "chuyên viên tư vấn môi trường": "Environmental Consultant",
    "chuyên viên dịch vụ chứng khoán": "Securities Service Specialist",
    "chuyên viên phát triển sản phẩm": "Product Development Specialist",
    "chuyên viên phát triển thị trường": "Market Development Specialist",
}

industry_map = {
    # Công nghệ và Viễn thông
    "CNTT": "Information Technology",
    "IT": "Information Technology",
    "công nghệ thông tin": "Information Technology",
    "viễn thông": "Telecommunications",
    "phần mềm": "Software Development",
    "phần cứng": "Hardware Development",
    "mạng": "Network Engineering",
    # Kinh doanh và Marketing
    "marketing": "Marketing",
    "tiếp thị": "Marketing",
    "bán hàng": "Sales",
    "kinh doanh": "Sales",
    "dịch vụ khách hàng": "Customer Service",
    # Tài chính và Kế toán
    "tài chính": "Finance",
    "ngân hàng": "Banking",
    "chứng khoán": "Securities",
    "đầu tư": "Investment",
    "bảo hiểm": "Insurance",
    "kế toán": "Accounting",
    "kiểm toán": "Auditing",
    # Giáo dục và Đào tạo
    "giáo dục": "Education",
    "đào tạo": "Education",
    # Sản xuất và Kỹ thuật
    "sản xuất": "Manufacturing",
    "vận hành sản xuất": "Production Operations",
    "cơ khí": "Mechanical Engineering",
    "điện tử": "Electronics",
    "điện lạnh": "Refrigeration",
    "ô tô": "Automotive",
    "tự động hóa": "Automation",
    "xây dựng": "Construction",
    # Y tế và Dược phẩm
    "y tế": "Healthcare",
    "chăm sóc sức khỏe": "Healthcare",
    "dược phẩm": "Pharmaceuticals",
    "bác sĩ": "Medical Practitioner",
    # Môi trường và Nông nghiệp
    "môi trường": "Environmental Services",
    "nông nghiệp": "Agriculture",
    # Bán lẻ và Bán sỉ
    "bán lẻ": "Retail",
    "bán sỉ": "Wholesale",
    # Bất động sản và Vận tải
    "bất động sản": "Real Estate",
    "giao nhận": "Logistics",
    "vận chuyển": "Logistics",
    "xuất nhập khẩu": "Import-Export",
    # Nghệ thuật và Thiết kế
    "mỹ thuật": "Art and Design",
    "thiết kế": "Design",
    "giải trí": "Entertainment",
    "quảng cáo": "Advertising",
    "truyền thông": "Media",
    # An toàn và Dịch vụ công cộng
    "an toàn lao động": "Occupational Safety",
    "dịch vụ công cộng": "Public Services",
}

skill_dict = [
    # Lập trình và công nghệ
    "python",
    "java",
    "sql",
    "học máy",
    "học sâu",
    ".NET",
    "c++",
    "c#",
    "javascript",
    "html",
    "css",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "r",
    "typescript",
    "lập trình shell",
    "git",
    "jira",
    "confluence",
    "gitlab",
    "bitbucket",
    "trello",
    "notion",
    "điện toán đám mây",
    "ci/cd pipelines",
    "microservices",
    "linux",
    "windows",
    "macos",
    "ubuntu",
    "centos",
    "dữ liệu lớn",
    "hadoop",
    "spark",
    "khai phá dữ liệu",
    # Cơ sở dữ liệu
    "phân tích dữ liệu",
    "khoa học dữ liệu",
    "sql server",
    "mysql",
    "mongodb",
    "oracle",
    "postgresql",
    "nosql",
    "cassandra",
    "redis",
    "elasticsearch",
    "kho dữ liệu",
    "hive",
    "trực quan hóa dữ liệu",
    "etl",
    "power bi",
    "tableau",
    "qlikview",
    # Công cụ văn phòng
    "excel",
    "powerpoint",
    "word",
    "microsoft office",
    "google sheets",
    "google docs",
    "quản lý dự án",
    "quản lý thời gian",
    "quản lý nguồn lực",
    "báo cáo",
    "microsoft project",
    "asana",
    "basecamp",
    "monday.com",
    # Marketing và Truyền thông
    "seo",
    "tiếp thị",
    "tiếp thị số",
    "tiếp thị nội dung",
    "tiếp thị mạng xã hội",
    "quảng cáo facebook",
    "quảng cáo google",
    "email marketing",
    "sáng tạo nội dung",
    "viết quảng cáo",
    "tiếp thị người ảnh hưởng",
    "mạng xã hội",
    "quản lý chiến dịch",
    "tối ưu hóa quảng cáo",
    "xây dựng thương hiệu",
    "phân tích thị trường",
    "phân khúc khách hàng",
    "chiến lược bán hàng",
    # Nền tảng Đám mây và DevOps
    "aws",
    "azure",
    "google cloud",
    "bảo mật đám mây",
    "tự động hóa đám mây",
    "kubernetes",
    "jenkins",
    "ansible",
    "terraform",
    "docker",
    "prometheus",
    "grafana",
    "cloudformation",
    "openstack",
    "ci/cd",
    "giám sát",
    "tự động hóa triển khai",
    # Quản lý phiên bản và công cụ hỗ trợ phát triển
    "svn",
    "quản lý phiên bản",
    "quản lý mã nguồn",
    "đánh giá mã",
    "tự động hóa kiểm thử",
    "tự động hóa xây dựng",
    "làm việc nhóm",
    "slack",
    "zoom",
    "teams",
    "skype",
    "webex",
    # Hệ điều hành và môi trường làm việc
    "mạng máy tính",
    "vpn",
    "active directory",
    "windows server",
    "bash",
    "powershell",
    "tường lửa",
    "kiểm tra bảo mật",
    "kiểm tra thâm nhập",
    "cấu hình mạng",
    "cấu hình vpn",
    "cân bằng tải",
    # Thiết kế đồ họa và Công cụ sáng tạo
    "photoshop",
    "illustrator",
    "canva",
    "indesign",
    "after effects",
    "premiere pro",
    "adobe xd",
    "figma",
    "blender",
    "3ds max",
    "maya",
    "chỉnh sửa video",
    "thiết kế đồ họa",
    "hoạt hình",
    "minh họa kỹ thuật số",
    "trải nghiệm người dùng",
    "giao diện người dùng",
    "phát triển prototype",
    "wireframing",
    # Phát triển front-end và back-end
    "react",
    "angular",
    "vue",
    "node.js",
    "django",
    "flask",
    "spring",
    "spring boot",
    "laravel",
    "asp.net",
    "bootstrap",
    "jquery",
    "redux",
    "next.js",
    "nuxt.js",
    "microfrontend",
    "phát triển web",
    "thiết kế responsive",
    # Phát triển ứng dụng di động
    "flutter",
    "react native",
    "xamarin",
    "ionic",
    "phát triển android",
    "phát triển ios",
    "thiết kế ứng dụng di động",
    "swiftui",
    "kotlin coroutines",
    "apple hci",
    "material design",
    # Kỹ năng mạng xã hội và các nền tảng phổ biến
    "tiktok",
    "youtube",
    "facebook",
    "instagram",
    "linkedin",
    "twitter",
    "zalo",
    "snapchat",
    "weibo",
    "wechat",
    "phân tích mạng xã hội",
    "tương tác cộng đồng",
    "lên lịch nội dung",
    # Các công cụ hỗ trợ làm việc nhóm và quản lý dự án
    "scrum",
    "agile",
    "kanban",
    "pmp",
    "vòng đời dự án",
    "mô hình thác nước",
    "biểu đồ gantt",
    "phân bổ nguồn lực",
    "quản lý chi phí",
    "quản lý rủi ro",
    "quản lý các bên liên quan",
    "jira",
    "monday.com",
    "asana",
    "quản lý công việc",
    # Kỹ năng phân tích và trực quan hóa dữ liệu
    "tableau",
    "power bi",
    "qlikview",
    "trực quan hóa dữ liệu",
    "phân tích",
    "google analytics",
    "phân tích phân khúc",
    "phân tích dự đoán",
    "phân tích khách hàng",
    "kể chuyện bằng dữ liệu",
    "phân tích chuỗi thời gian",
    "a/b testing",
    "mô hình hóa thống kê",
    "lập trình r",
    "sas",
    "pipeline học máy",
    # Kỹ năng mềm
    "lãnh đạo",
    "làm việc nhóm",
    "giao tiếp",
    "giải quyết vấn đề",
    "quản lý thời gian",
    "tư duy phản biện",
    "khả năng thích ứng",
    "trí tuệ cảm xúc",
    "dịch vụ khách hàng",
    "thuyết trình",
    "đàm phán",
    "giải quyết xung đột",
    "tự tạo động lực",
    "hợp tác",
    "cố vấn",
    "tư duy chiến lược",
    "networking",
    "tư duy phân tích",
    # Các kỹ năng khác
    "phân tích tài chính",
    "phân tích kinh doanh",
    "thuế",
    "đánh giá rủi ro",
    "kế toán",
    "quản trị doanh nghiệp",
    "cải tiến quy trình",
    "đảm bảo chất lượng",
    "tuân thủ dữ liệu",
    "tự động hóa kiểm thử",
    "kiểm thử thủ công",
    "a/b testing",
    "nghiên cứu người dùng",
    "phát triển sản phẩm",
    "lập bản đồ hành trình khách hàng",
    "sự hài lòng của khách hàng",
    "nghiên cứu thị trường",
    "lập kế hoạch tài chính",
    "phân tích chi phí",
    "quản lý chuỗi cung ứng",
    "quản lý hậu cần",
    "quản lý kho",
]

stop_words_vi = {
    "và",
    "là",
    "các",
    "của",
    "để",
    "trong",
    "với",
    "một",
    "những",
    "được",
    "bởi",
    "như",
    "khi",
    "này",
    "sẽ",
    "đã",
    "từ",
    "lại",
    "nên",
    "ra",
    "hơn",
    "cùng",
    "như",
    "thì",
    "ở",
    "nếu",
    "sau",
    "còn",
    "làm",
    "trên",
    "xuống",
    "vì",
    "lúc",
    "nào",
    "phải",
    "gì",
    "ai",
    "sao",
    "bao nhiêu",
    "đến",
    "nhỏ",
    "to",
    "thế",
    "chính",
    "cả",
    "người",
    "chúng",
    "ta",
    "tôi",
    "bạn",
    "anh",
    "chị",
    "ông",
    "bà",
    "chú",
    "cô",
    "nó",
    "ấy",
    "kia",
    "ấy",
    "nọ",
    "mỗi",
    "mọi",
    "rất",
    "không",
    "nhà",
    "cái",
    "gần",
    "xa",
    "vậy",
    "mà",
    "nơi",
    "dưới",
    "thông qua",
    "tại",
    "do",
    "trước",
    "sau",
    "qua",
    "để",
    "khoảng",
    "nữa",
    "sắp",
    "đều",
    "vẫn",
    "vào",
    "cùng",
    "theo",
    "nhóm",
    "từng",
    "một",
    "hơn",
    "lớn",
    "nhiều",
    "ít",
    "cả",
    "khắp",
    "gặp",
    "mới",
    "nơi",
    "tại",
    "qua",
    "chỉ",
    "đang",
    "mỗi",
    "cả",
    "giữa",
    "tất cả",
    "không chỉ",
    "phía",
    "theo",
    "vài",
    "lẫn",
    "chỗ",
    "khoảng",
    "cách",
    "bao",
    "gần",
    "chỗ",
    "gọi",
    "lấy",
    "gì",
    "đâu",
    "có",
    "đấy",
    "mình",
    "tới",
    "nên",
    "cách",
    "nhiều",
    "có thể",
    "bao lâu",
    "thế nào",
    "bởi vì",
    "thế nhưng",
    "cũng như",
    "mặc dù",
    "tuy nhiên",
    "ngay cả",
    "cho dù",
    "vì vậy",
    "do đó",
    "lại nữa",
    "tại sao",
    "bao giờ",
    "bất cứ",
    "dẫu sao",
    "hết",
    "lại",
    "nào",
    "mất",
    "cả",
    "từng",
    "vậy là",
    "khắp",
    "thường",
    "lúc nào",
    "chút",
    "ít",
    "hết sức",
    "dưới",
    "bên trên",
}
